title: Welcome to my GitHub page ^_^
author: code4Y
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I started to learn GitHub as it seems to be one of the top tools to contribute to open source 
  development and collaboration. Here we get to work with experts on their projects, under their
  guidance and a friendly environment. We get to work with awesome people and get to learn and 
  share knowledge.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
